### ISSUE TITLE
Remove default schemas or add ability to overwrite them 

### ISSUE THREAD

**Issue by Mvwivs** [agentlab/sparql-jsld-client#11]
Default schemas are always added to [ObjectProviderImpl.ts](https://github.com/agentlab/sparql-jsld-client/blob/4d299a9d9cfa32936787703685529ce72aa2b685/src/ObjectProviderImpl.ts#L354)
```js
  public constructor() {
    console.log('Create ObjectProviderImpl');
    this.addSchema(ResourceSchema);
    this.addSchema(ClassSchema);

    this.addSchema(ArtifactShapeSchema);
    this.addSchema(PropertyShapeSchema);
  }
```
But `addSchema` doesn't allow to rewrite them:
```js
  addSchema(schema: JSONSchema6forRdf): void {
    const uri = this.sparqlGen.abbreviateIri(schema['@id']);
    if (!this.schemas[uri]) this.schemas[uri] = schema;
  }
```
This becomes a problem when, for example, `'@type': 'sh:PropertyShape'` is mentioned in custom schema in request. Engine then uses default `PropertyShapeSchema` and there is no way for user to provide his own.

**Comment by amivanoff** [comment]
If you need different properties in schema you could create new schema with unique schema IRI targeting same targetClass.
Or you could redefine default schemas globally at startup.
