### ISSUE TITLE
Remove rm mentions

### ISSUE THREAD

**Issue by Mvwivs** [agentlab/sparql-jsld-client#7]
Forlder src should not contain any **rm** mentions (eg [ObjectProviderImpl.ts](https://github.com/agentlab/sparql-jsld-client/blob/4d299a9d9cfa32936787703685529ce72aa2b685/src/ObjectProviderImpl.ts#L684))

Another example is `ArtifactShapeSchema` with these fields:
```js
{ //...
  inCreationMenu: 'rm:inCreationMenu',
  defaultIndividNs: 'rm:defaultIndividNs',
  defaultFormat: 'rm:defaultFormat',
  iconReference: 'rm:iconReference',
}
```
`ArtifactShapeSchema` and `PropertyShapeSchema` **should not** contain any rm fields as they are added to provider by default

**Comment by amivanoff** [comment]
It's our extension of standard SHACL vocabulary (like DASH). Did not get from issue description , why our custom namespace prefix should not be in @context section.
